package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type ResourceMapping struct {
	LegacyType   string
	UnifiedType  string
	ProviderType string
}

var resourceMappings = []ResourceMapping{
	{LegacyType: "aws_s3_bucket", UnifiedType: "multicloud_storage_bucket", ProviderType: "aws"},
	{LegacyType: "aws_instance", UnifiedType: "multicloud_virtual_machine", ProviderType: "aws"},
	{LegacyType: "aws_vpc", UnifiedType: "multicloud_virtual_network", ProviderType: "aws"},
	{LegacyType: "aws_db_instance", UnifiedType: "multicloud_db_instance", ProviderType: "aws"},
	{LegacyType: "aws_security_group", UnifiedType: "multicloud_security_group", ProviderType: "aws"},
	{LegacyType: "google_storage_bucket", UnifiedType: "multicloud_storage_bucket", ProviderType: "gcp"},
	{LegacyType: "google_compute_instance", UnifiedType: "multicloud_virtual_machine", ProviderType: "gcp"},
	{LegacyType: "google_compute_network", UnifiedType: "multicloud_virtual_network", ProviderType: "gcp"},
	{LegacyType: "google_sql_database_instance", UnifiedType: "multicloud_db_instance", ProviderType: "gcp"},
	{LegacyType: "google_compute_firewall", UnifiedType: "multicloud_security_group", ProviderType: "gcp"},
	{LegacyType: "azurerm_storage_container", UnifiedType: "multicloud_storage_bucket", ProviderType: "azure"},
	{LegacyType: "azurerm_linux_virtual_machine", UnifiedType: "multicloud_virtual_machine", ProviderType: "azure"},
	{LegacyType: "azurerm_virtual_network", UnifiedType: "multicloud_virtual_network", ProviderType: "azure"},
	{LegacyType: "azurerm_postgresql_server", UnifiedType: "multicloud_db_instance", ProviderType: "azure"},
	{LegacyType: "azurerm_network_security_group", UnifiedType: "multicloud_security_group", ProviderType: "azure"},
}

var resourceRegex = regexp.MustCompile(`resource\s+"([a-zA-Z0-9_]+)"\s+"([a-zA-Z0-9_]+)"\s*\{([^}]*)\}`)
var attrRegex = regexp.MustCompile(`([a-zA-Z0-9_]+)\s*=\s*(.+)`)

func main() {
	inputDirFlag := flag.String("input-dir", ".", "Path to directory containing legacy cloud Terraform files")
	outFileFlag := flag.String("out-file", "multicloud_migrated.tf", "Output path for converted multi-cloud HCL manifest")
	migrateStateFlag := flag.Bool("migrate-state", false, "Generate state migration script (migrate_state.sh)")
	dryRunFlag := flag.Bool("dry-run", false, "Preview converted HCL and state moves without writing files")
	flag.Parse()

	fmt.Println("======================================================================")
	fmt.Println("  MULTI-CLOUD TERRAFORM HCL CONVERTER & STATE MIGRATOR")
	fmt.Println("======================================================================")

	files, err := filepath.Glob(filepath.Join(*inputDirFlag, "*.tf"))
	if err != nil || len(files) == 0 {
		fmt.Printf("[tf-migrate] No .tf files found in directory '%s'\n", *inputDirFlag)
		return
	}

	var convertedHCL strings.Builder
	var stateCommands []string

	convertedHCL.WriteString("# Auto-generated by tf-migrate - Multi-Cloud Terraform Provider Migration Tool\n\n")

	convertedCount := 0
	for _, file := range files {
		if strings.HasSuffix(file, "multicloud_migrated.tf") {
			continue
		}

		/* #nosec G304 */
		content, err := os.ReadFile(file)
		if err != nil {
			continue
		}

		matches := resourceRegex.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) < 4 {
				continue
			}

			legacyType := match[1]
			resName := match[2]
			blockBody := match[3]

			for _, mapping := range resourceMappings {
				if mapping.LegacyType == legacyType {
					convertedCount++
					fmt.Printf("[tf-migrate] Migrating %s.%s -> %s.%s (provider_type = \"%s\")\n", legacyType, resName, mapping.UnifiedType, resName, mapping.ProviderType)

					convertedHCL.WriteString(fmt.Sprintf("resource \"%s\" \"%s\" {\n", mapping.UnifiedType, resName))
					convertedHCL.WriteString(fmt.Sprintf("  provider_type = \"%s\"\n", mapping.ProviderType))

					// Extract extra non-standard attributes for extra_config map
					var extraConfig []string
					attrMatches := attrRegex.FindAllStringSubmatch(blockBody, -1)
					for _, am := range attrMatches {
						key := strings.TrimSpace(am[1])
						val := strings.TrimSpace(am[2])
						if isStandardAttr(key) {
							convertedHCL.WriteString(fmt.Sprintf("  %s = %s\n", key, val))
						} else {
							extraKey := fmt.Sprintf("%s_%s", mapping.ProviderType, key)
							extraConfig = append(extraConfig, fmt.Sprintf("    \"%s\" = %s", extraKey, val))
						}
					}

					if len(extraConfig) > 0 {
						convertedHCL.WriteString("  extra_config = {\n")
						for _, ec := range extraConfig {
							convertedHCL.WriteString(ec + "\n")
						}
						convertedHCL.WriteString("  }\n")
					}

					convertedHCL.WriteString("}\n\n")

					stateCommands = append(stateCommands, fmt.Sprintf("terraform state mv %s.%s %s.%s", legacyType, resName, mapping.UnifiedType, resName))
				}
			}
		}
	}

	if convertedCount == 0 {
		fmt.Println("[tf-migrate] No legacy AWS, GCP, or Azure resources detected for conversion.")
		return
	}

	if *dryRunFlag {
		fmt.Println("\n[tf-migrate] Dry-run mode enabled. Converted HCL Preview:")
		fmt.Println(convertedHCL.String())
		if *migrateStateFlag {
			fmt.Println("[tf-migrate] State Migration Commands Preview:")
			for _, cmd := range stateCommands {
				fmt.Println("  " + cmd)
			}
		}
		return
	}

	cleanOutPath := filepath.Clean(*outFileFlag)
	/* #nosec G306 G703 */
	if err := os.WriteFile(cleanOutPath, []byte(convertedHCL.String()), 0600); err != nil {
		fmt.Printf("Error writing converted HCL file: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("\n[tf-migrate] Converted %d legacy resources to %s\n", convertedCount, cleanOutPath)

	if *migrateStateFlag {
		scriptPath := filepath.Clean("migrate_state.sh")
		scriptContent := "#!/bin/bash\n# Terraform State Migration Script generated by tf-migrate\nset -e\n\n" + strings.Join(stateCommands, "\n") + "\n"
		/* #nosec G306 G703 */
		if err := os.WriteFile(scriptPath, []byte(scriptContent), 0600); err != nil {
			fmt.Printf("Error writing state migration script: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("[tf-migrate] Generated state migration script to %s\n", scriptPath)
	}
}

func isStandardAttr(attr string) bool {
	standard := map[string]bool{
		"bucket_name":        true,
		"region":             true,
		"versioning_enabled": true,
		"encryption_enabled": true,
		"instance_type":      true,
		"name":               true,
	}
	return standard[attr]
}
